---
title: 'BUAN6356: Data Visualization'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float: yes
date: "`r Sys.Date()`"
title2: Using Boston Housing Data
---

### *R Code: Session2*


### 1. Load packages and check loading  
```{r loadPackages, warning=FALSE, message=FALSE, results='hide' }
if(!require("pacman")) install.packages("pacman")
pacman::p_load(forecast, tidyverse, gplots, GGally, mosaic,
               scales, mosaic, mapproj, mlbench, data.table)
search()
theme_set(theme_classic()) # to set a basic theme for visualization
```


### 2. Read in Boston Housing Data from *mlbench* package  
```{r readData} ## naming the code blocks
## Read Boston Housing data
data("BostonHousing")
  
#default: data frame
housing.df <- BostonHousing
dim(housing.df)
str(housing.df)
search()
# preferred: data.table

vignette(package="data.table") #learn more about data table
housing.dt <- setDT(BostonHousing) #converting to data table as data table runs faster
housing.dt[, cat.medv := ifelse(medv>30,1,0)] #create a categorical medv variable

```

### 3. Generate Data Visualizations   
```{r 1Scatter}
# use alpha for transperancy [0,1]
ggplot(housing.df) +
  geom_point(aes(x = lstat, y = medv), color = "tomato2", alpha = 0.4) +
  ggtitle("Median Housing Price")

```
#Bar charts are for categorical variables where as histogram are used to plot continuous variables
  
```{r 2Barchart} 
# Barchart - Is there any difference in mean(medv) by chas?
# stat = identity to specify that dont plot just the frequency distribution but use the statistics (here mean MEDV) to plot the graph 
#Also we can use geom_col() instead of stat = identity
data.for.plot <- housing.dt[, .(meanMEDV = mean(medv)), by=chas]
ggplot(data.for.plot) + 
  geom_bar(aes(x = chas, y = meanMEDV), stat = "identity", width =.4, fill="seagreen") +
  coord_flip() +
  ylab("mean home price") +
  ggtitle("Average Median Housing Price")

# Barchart - Are there propotionately more high-value homes when chas=1?
data.for.plot2 <- housing.dt[, .(percent_medv = sum(cat.medv)*100/ .N), keyby=chas]
ggplot(data.for.plot2) +
  coord_flip() +
  geom_bar(aes(x=chas, y = percent_medv), stat = "identity", width = 0.4, 
  fill = "wheat", color = "brown2") +
  ylab("Percent homes > $30K") +
  ggtitle("Percentage of High-Value Homes by Chas")
```


```{r 3Histogram}
# histogram of medv variable - does it look like a normal distribution?
ggplot(housing.dt) +
  geom_histogram(aes(x = medv), binwidth = 3, fill = "goldenrod2") +
  ggtitle("Histogram of MEDV Variable")

```


```{r 4BoxPlot}
ggplot(housing.dt) +
  geom_boxplot(aes(x = chas, y = medv), 
               fill = "gold1", outlier.color = "firebrick2") + 
  xlab("Charles River Dummy") + ggtitle("Where are the Outliers?")

```
  

```{r 5Heatmaps, warning=FALSE, message=FALSE}
# simple heatmap for correlations (without values)
heatmap(cor(housing.dt[,!c("chas")]), Rowv = NA, Colv = NA)

# heatmap using ggplot
# using reshape package to to generate input for the plot 
library(reshape)
cor.mat <- round(cor(housing.dt[,!c("chas", "cat.medv")]),2) # rounded correlation matrix 
melted.cor.mat <- melt(cor.mat) 
ggplot(melted.cor.mat, aes(x = X1, y = X2, fill = value)) + 
  scale_fill_gradient(low="wheat", high="orangered") +
  geom_tile() + 
  geom_text(aes(x = X1, y = X2, label = value)) +
  ggtitle("Which Variables Are Highly Correlated?")

```

```{r 6MultiDimensional}
# example of multidimensional plot - use third variable for color coding
ggplot(housing.dt, aes(y = nox, x = lstat, color= as.factor(cat.medv))) +
  geom_point(alpha = 0.6)
```


```{r 7PanelPlots}
# Computing mean MEDV by RAD & CHAS
data.for.plot3 <- housing.dt[, .(meanMedv = mean(medv)), keyby=.(rad, chas)]
ggplot(data.for.plot3) +
  geom_bar(aes(x = as.factor(rad), y = `meanMedv`), stat = "identity", 
           fill = "wheat1", color = "red") +
  xlab("accessability to radial highways") + facet_grid(chas ~ .) 

```

 
```{r 8ScatterPlotMatrix, message=FALSE}
plot(housing.dt[, c("crim", "indus", "lstat", "medv")])
# Alternative -- reports correlation coefficient
# using GGally package
ggpairs(housing.dt[, c("crim", "indus", "lstat", "medv")])

```

```{r 9Maps, warning=FALSE, message=FALSE}
# using mosaic package
gdp.df <- read.csv("gdp.csv", skip = 4, stringsAsFactors = FALSE) 
names(gdp.df)[5] <- "GDP2015"
happiness.df <- read.csv("Veerhoven.csv")

# World Map: GDP by Counrty
mWorldMap(gdp.df, key = "Country.Name", fill = "GDP2015") + 
  coord_map()

# World Map: Which Countries Have the Happiest People?
mWorldMap(happiness.df, key = "Nation", fill = "Score") + coord_map() + 
  scale_fill_continuous(name = "Happiness")

```
